package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

func cmdSetup(args []string) error {
	fs := flag.NewFlagSet("setup", flag.ContinueOnError)
	var yes, force bool
	fs.BoolVar(&yes, "yes", false, "non-interactive: accept defaults/setup.conf/flags")
	fs.BoolVar(&force, "force", false, "regenerate ALL secrets (DESTRUCTIVE for live data)")
	repo := repoDir()
	c := LoadConfig(repo)
	fs.StringVar(&c.ServerIP, "server-ip", c.ServerIP, "server LAN IP")
	fs.StringVar(&c.TZ, "tz", c.TZ, "timezone")
	fs.StringVar(&c.ACMEEmail, "email", c.ACMEEmail, "admin email (Let's Encrypt contact)")
	fs.StringVar(&c.VaultHost, "vault-host", c.VaultHost, "Vaultwarden hostname")
	fs.StringVar(&c.CloudHost, "cloud-host", c.CloudHost, "Nextcloud hostname")
	fs.StringVar(&c.PiholeHost, "pihole-host", c.PiholeHost, "Pi-hole hostname")
	fs.StringVar(&c.CAHost, "ca-host", c.CAHost, "cert-download hostname")
	fs.BoolVar(&c.UseLE, "letsencrypt", c.UseLE, "use Let's Encrypt instead of local CA")
	fs.IntVar(&c.VWPort, "vw-port", c.VWPort, "Vaultwarden host port")
	fs.IntVar(&c.NCPort, "nc-port", c.NCPort, "Nextcloud host port")
	fs.IntVar(&c.PiholeWebPort, "pihole-port", c.PiholeWebPort, "Pi-hole web port")
	fs.StringVar(&c.PiholeDNSBind, "pihole-dns-bind", c.PiholeDNSBind, "Pi-hole :53 bind IP")
	fs.BoolVar(&c.VWSignupsAllowed, "vw-signups", c.VWSignupsAllowed, "allow open Vaultwarden signups")
	if err := fs.Parse(args); err != nil {
		return err
	}

	if !yes && isTTY() {
		c = promptConfig(c)
	}
	c.Normalize()
	if err := c.Save(repo); err != nil {
		return err
	}
	fmt.Println("Saved", filepath.Join(repo, confFile))

	secrets, err := c.Generate(repo, force)
	if err != nil {
		return err
	}
	if len(secrets) > 0 {
		var b strings.Builder
		b.WriteString("# Generated by hsctl — store in Vaultwarden, then delete this file.\n")
		for _, s := range secrets {
			fmt.Fprintf(&b, "%-26s %s\n", s.Label, s.Value)
		}
		if err := appendFile(filepath.Join(repo, ".secrets.txt"), b.String()); err != nil {
			return err
		}
		fmt.Println("\n============ NEW LOGINS (saved to .secrets.txt) ============")
		fmt.Print(b.String())
		fmt.Println("===========================================================")
	} else {
		fmt.Println("All .env files already exist (nothing regenerated). Use --force to recreate.")
	}
	fmt.Println("\nNext: hsctl up   then   hsctl get-ca")
	return nil
}

func isTTY() bool {
	fi, err := os.Stdin.Stat()
	return err == nil && (fi.Mode()&os.ModeCharDevice) != 0
}

var stdinReader = bufio.NewReader(os.Stdin)

func ask(prompt, def string) string {
	fmt.Printf("  %s [%s]: ", prompt, def)
	line, _ := stdinReader.ReadString('\n')
	if line = strings.TrimSpace(line); line == "" {
		return def
	}
	return line
}

func askYN(prompt string, def bool) bool {
	d := "y/N"
	if def {
		d = "Y/n"
	}
	fmt.Printf("  %s [%s]: ", prompt, d)
	line, _ := stdinReader.ReadString('\n')
	line = strings.TrimSpace(strings.ToLower(line))
	if line == "" {
		return def
	}
	return strings.HasPrefix(line, "y")
}

func promptConfig(c Config) Config {
	fmt.Println("== Configure (Enter accepts each [default]) ==")
	c.ServerIP = ask("Server LAN IP", c.ServerIP)
	c.TZ = ask("Timezone", c.TZ)
	c.ACMEEmail = ask("Admin email (Let's Encrypt contact)", c.ACMEEmail)
	c.VaultHost = ask("Vaultwarden hostname", c.VaultHost)
	c.CloudHost = ask("Nextcloud hostname", c.CloudHost)
	c.PiholeHost = ask("Pi-hole hostname", c.PiholeHost)
	c.CAHost = ask("Cert-download hostname", c.CAHost)
	c.HomeHost = ask("Dashboard (web UI) hostname", c.HomeHost)
	c.UseLE = askYN("Use Let's Encrypt instead of a local CA?", c.UseLE)
	c.VWPort = atoiDef(ask("Vaultwarden host port", strconv.Itoa(c.VWPort)), c.VWPort)
	c.NCPort = atoiDef(ask("Nextcloud host port", strconv.Itoa(c.NCPort)), c.NCPort)
	c.PiholeWebPort = atoiDef(ask("Pi-hole web port", strconv.Itoa(c.PiholeWebPort)), c.PiholeWebPort)
	c.UIPort = atoiDef(ask("Dashboard (web UI) port", strconv.Itoa(c.UIPort)), c.UIPort)
	// derived defaults follow the IP just entered
	dnsDef := c.PiholeDNSBind
	if dnsDef == "" {
		if dnsDef = "0.0.0.0"; portBusy(53) {
			dnsDef = c.ServerIP
		}
	}
	c.PiholeDNSBind = ask("Pi-hole DNS bind IP", dnsDef)
	c.VWSignupsAllowed = askYN("Allow open Vaultwarden signups?", c.VWSignupsAllowed)
	return c
}

func appendFile(path, content string) error {
	f, err := os.OpenFile(path, os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0600)
	if err != nil {
		return err
	}
	defer f.Close()
	_, err = f.WriteString(content)
	return err
}
